### ISSUE TITLE
SSH could not read data: Error waiting on socket

### ISSUE THREAD

**Issue by cbanciu667** [fluxcd/image-automation-controller#342]
Hi guys,

We are having this issue since some time and we hopped that by upgrading this would be fixed. 
Latest FluxCD version did not fixed it unfortunately (v.0.28.5). 

We are using EKS in AWS and i followed every guide or best practice from FluxCD.

Versions used: [v0.28.5](https://github.com/fluxcd/flux2/releases/tag/v0.28.5) 
gotk-sync.yaml:
  apiVersion: source.toolkit.fluxcd.io/v1beta2
  kind: GitRepository
  metadata:
    name: flux-system
    namespace: flux-system
  spec:
    interval: 1m
    timeout: 50s
 
Please fix this as the developers can not test their new deployments and our CD pipelines are blocked.

Thanks.

**Comment by pjbgf** [comment]
@cbanciu667 thank you for reporting this issue. We have recently fixed this problem with our new experimental transport. 

Now that you are on the latest version of the controllers, can you please just `opt-in` to the experimental transport as detailed below and hopefully it will resolve your issue:
https://github.com/fluxcd/source-controller/issues/636#issuecomment-1080789920

**Comment by pjbgf** [comment]
@jdiegosierra do you mind confirming what version of `image-automation-controller` you are using?

**Comment by jdiegosierra** [comment]
@pjbgf

```
flux bootstrap git \
  --url=ssh://git@bitbucket.org/my_organization/infrastructure-deployment \
  --branch=master \
  --path=kubernetes/clusters/development \
  --private-key-file=/Users/my_user/.ssh/id_rsa \
  --context=arn:aws:eks:eu-west-1:my_aws_account_id:cluster/development \
  --components-extra=image-reflector-controller,image-automation-controller
```

```
    Image:         ghcr.io/fluxcd/image-automation-controller:v0.21.3
    Image ID:      docker-pullable://ghcr.io/fluxcd/image-automation-controller@sha256:de3bc7e17ddeebf8cc96ac1df8b658557556f30f0d1a521ddc703a6ca5b20a1b

    Image:         ghcr.io/fluxcd/source-controller:v0.22.5
    Image ID:      docker-pullable://ghcr.io/fluxcd/source-controller@sha256:a7eb65e2a015d9b9c5f125d440381d33c2aa6ca363ad88a9aa66f4cc09ddc4a7

    Image:         ghcr.io/fluxcd/image-reflector-controller:v0.17.1
    Image ID:      docker-pullable://ghcr.io/fluxcd/image-reflector-controller@sha256:01f68bfa1a242a2fae7071dc1583ae33b620a8439f862a2d33bbc3c71bbad04a
```

**Comment by jdiegosierra** [comment]
Is there any workaround? Maybe setting a stable version? I'm totally blocked with this and can't get any image to be upgraded automatically.

**Comment by jdiegosierra** [comment]
For those who are blocked, I'm using Keel Tool together with Flux and it works fine. So I'm using Keel for image automation and Flux for infrastructure automation.

**Comment by cbanciu667** [comment]
I activated the experimental transport but now I get this error:

```
2022-04-08T14:50:12.355Z error ImageUpdateAutomation/flux-system.flux-system - Reconciler error unable to clone &#39;ssh://git@bitbucket.org/.../repo.git&#39;: ssh: rejected: administratively prohibited (cannot open additional channels)
2022-04-08T14:50:59.884Z error ImageUpdateAutomation/flux-system.flux-system - Reconciler error unable to clone &#39;ssh://git@bitbucket.org/...../repo.git&#39;: EOF
2022-04-08T14:51:10.822Z error ImageUpdateAutomation/flux-system.flux-system - Reconciler error unable to clone &#39;ssh://git@bitbucket.org/..../repo.git&#39;: ssh: r2022-04-08T14:53:11.375Z info ImageRepository/tenant-management-svc.flux-system - reconciliation finished in 59.536288ms, next run in 1m0s
```

However the situation is a little better in the sense that the images are randomly updated. Sometimes yes, sometimes not.

**Comment by pjbgf** [comment]
I have recently merged [some fixes](https://github.com/fluxcd/source-controller/pull/658) on `source-controller` that should fix the `EOL` and `early EOF` for cached connections that became stale. Once a version is cut, I will be able to release a new image for `image-automation-controller` with those improvements.

In the mean time, I create a [draft PR](https://github.com/fluxcd/image-automation-controller/pull/346), so you can either:

1) Wait until the changes are released (at some point next week).
2) Test changes using my image: `quay.io/paulinhu/image-automation-controller:selfheal@sha256:0c78d0ff5aec404c724b623e9d4ae00d5c0348320c397626900d1e073e1d7ac5`:
3) Create your own image using the PR and running: `IMG=repo/and/image-name TAG=your-tag BUILD_PLATFORMS="linux/amd64" BUILD_ARGS="--push" make docker-build`

If you could test ahead of the release and confirm it fixes/improves your issue that would be great.
On a side note, do either of you have multiple concurrent `BitBucket` sources running at similar intervals?

**Comment by cbanciu667** [comment]
@pjbgf 

I am using the image provided in step 2 in one of our clusters and I still see occasional errors like "unable to clone -  transport closed", as before, but they are reduced in number.

I will use this image in all our 4 clusters and test further the image updates. I will come back with feedback after 1-2 days.
Btw. we are using a technical git user with same ssh key across all clusters. Could that cause an issue with Bitbucket because repetitive git calls ?

**Comment by pjbgf** [comment]
@cbanciu667 thank you for testing and reporting back. 

In terms of BitBucket's rate limiting, it will depend on the frequency of the calls. They do have a very high [limit for authenticated connections](https://support.atlassian.com/bitbucket-cloud/docs/api-request-limits/). As long as you don't reach their threshold, and are not generating too many authentication failures, you are less likely to be throttled. 

I know that the SSH protocol first attempts an "anonymous connection" before providing authentication, I am not sure whether BitBucket counts for those. If they do, then your limit is about 60 requests per hour per source IP.

**Comment by DaemonDude23** [comment]
Yesterday I deployed the image mentioned in step 2. Same as with @cbanciu667 , there's a significant improvement with reduction of errors (I'm on BitBucket as well). I'm looking forward to upcoming releases containing these changes.

**Comment by cbanciu667** [comment]
After checking again the logs from our clusters, the SSH errors as bellow are still there, but the new images are committed somehow. The situation has improved so we will continue to use the provided testing image until further version/fix is released.

"logger":"controller.imageupdateautomation","msg":"Reconciler error","reconciler group":"image.toolkit.fluxcd.io","reconciler kind":"ImageUpdateAutomation","name":"flux-system","namespace":"flux-system","error":"unable to clone 'ssh://git@bitbucket.org/xrepo.git': SSH could not read data: Error waiting on socket

**Comment by cbanciu667** [comment]
Hi @pjbgf ,

Does it makes sense to keep this issue opened ? From my side, even if the random errors are there,  the images get updated somehow and the CD part seems to work without any issue since 2 feels ago. Which is the most essential part.
You know better what is required from the coding side or if there are any pending changes.

Thanks a lot.

Cos

**Comment by pjbgf** [comment]
@cbanciu667 happy to go ahead and close it.

We will keep tracking the overall improvements on the Git implementation on the linked issue.
